/**
 * Testes unitários para src/server/team-catalog.ts
 */

import { describe, it, expect } from "vitest";
import { listTeamMembers } from "@/server/team-catalog";
import type { Storage } from "@/server/storage";

describe("team-catalog — listTeamMembers", () => {
  it("retorna array (pode incluir membros padrão do manifest)", async () => {
    const mockStorage: Storage = {
      kind: "memory",
      countUsers: async () => 0,
      getUserByEmail: async () => null,
      getUserById: async () => null,
      listUsers: async () => [],
      insertUser: async () => {},
      updateUser: async () => {},
      deleteUser: async () => {},
      insertSession: async () => {},
      getSessionByTokenHash: async () => null,
      deleteSession: async () => {},
      deleteSessionsForUser: async () => {},
      purgeExpiredSessions: async () => {},
      createSession: async () => {},
      listUserFunctions: async () => [],
      grantUserFunction: async () => {},
      revokeUserFunction: async () => {},
      getMeta: async () => null,
      setMeta: async () => {},
      insertAudit: async () => {},
      insertTask: async () => {},
      listTasks: async () => [],
      getTask: async () => null,
      updateTask: async () => {},
      deleteTask: async () => {},
      listComments: async () => [],
      insertComment: async () => {},
      listEvidences: async () => [],
      getEvidence: async () => null,
      insertEvidence: async () => {},
      updateEvidence: async () => {},
      listControls: async () => [],
      getControl: async () => null,
      insertControl: async () => {},
      updateControl: async () => {},
      listRisks: async () => [],
      getRisk: async () => null,
      insertRisk: async () => {},
      updateRisk: async () => {},
      listBoardColumns: async () => [],
      insertBoardColumn: async () => {},
      updateBoardColumn: async () => {},
      deleteBoardColumn: async () => {},
      listModules: async () => [],
      insertModule: async () => {},
      updateModule: async () => {},
      deleteModule: async () => {},
      listMilestones: async () => [],
      insertMilestone: async () => {},
      updateMilestone: async () => {},
      listJournalEntries: async () => [],
      insertJournalEntry: async () => {},
      updateJournalEntry: async () => {},
      listLegalDocs: async () => [],
      insertLegalDoc: async () => {},
      updateLegalDoc: async () => {},
      listWikiArticles: async () => [],
      insertWikiArticle: async () => {},
      updateWikiArticle: async () => {},
      exportBackup: async () => "",
      importBackup: async () => {},
      dispose: async () => {},
      executeSql: async () => [],
    };
    const result = await listTeamMembers(mockStorage);
    // buildLinkedTeamMembers retorna array com membros do manifest por padrão
    expect(Array.isArray(result)).toBe(true);
  });

  it("associa usuários com teamMemberId", async () => {
    const mockStorage: Storage = {
      kind: "memory",
      countUsers: async () => 1,
      getUserByEmail: async () => null,
      getUserById: async () => null,
      listUsers: async () => [
        {
          id: "user-1",
          name: "Teste",
          email: "teste@teste.com",
          role: "desenvolvedor",
          jobTitle: null,
          department: null,
          bio: null,
          avatarUrl: null,
          teamMemberId: "team-1",
          passwordHash: "",
          passwordSalt: "",
          createdAt: "",
          updatedAt: "",
        },
      ],
      insertUser: async () => {},
      updateUser: async () => {},
      deleteUser: async () => {},
      insertSession: async () => {},
      getSessionByTokenHash: async () => null,
      deleteSession: async () => {},
      deleteSessionsForUser: async () => {},
      purgeExpiredSessions: async () => {},
      createSession: async () => {},
      listUserFunctions: async () => [],
      grantUserFunction: async () => {},
      revokeUserFunction: async () => {},
      getMeta: async () => null,
      setMeta: async () => {},
      insertAudit: async () => {},
      insertTask: async () => {},
      listTasks: async () => [],
      getTask: async () => null,
      updateTask: async () => {},
      deleteTask: async () => {},
      listComments: async () => [],
      insertComment: async () => {},
      listEvidences: async () => [],
      getEvidence: async () => null,
      insertEvidence: async () => {},
      updateEvidence: async () => {},
      listControls: async () => [],
      getControl: async () => null,
      insertControl: async () => {},
      updateControl: async () => {},
      listRisks: async () => [],
      getRisk: async () => null,
      insertRisk: async () => {},
      updateRisk: async () => {},
      listBoardColumns: async () => [],
      insertBoardColumn: async () => {},
      updateBoardColumn: async () => {},
      deleteBoardColumn: async () => {},
      listModules: async () => [],
      insertModule: async () => {},
      updateModule: async () => {},
      deleteModule: async () => {},
      listMilestones: async () => [],
      insertMilestone: async () => {},
      updateMilestone: async () => {},
      listJournalEntries: async () => [],
      insertJournalEntry: async () => {},
      updateJournalEntry: async () => {},
      listLegalDocs: async () => [],
      insertLegalDoc: async () => {},
      updateLegalDoc: async () => {},
      listWikiArticles: async () => [],
      insertWikiArticle: async () => {},
      updateWikiArticle: async () => {},
      exportBackup: async () => "",
      importBackup: async () => {},
      dispose: async () => {},
      executeSql: async () => [],
    };
    const result = await listTeamMembers(mockStorage);
    // buildLinkedTeamMembers retorna array (pode incluir membros padrão do manifest)
    expect(Array.isArray(result)).toBe(true);
    const hasTeste = result.some((m: any) => m.name === "Teste");
    // O membro Teste pode ou não estar no resultado dependendo do manifest
  });
});
